### ISSUE TITLE
config file for HiFi-Codec-24k-240d

### ISSUE THREAD

**Issue by wblgers** [yangdongchao/AcademiCodec#15]
Hi,

Thanks for your great work!
can you share the config file for HiFi-Codec-24k-240d?

**Comment by yangdongchao** [comment]
> Hi,
> 
> Thanks for your great work! can you share the config file for HiFi-Codec-24k-240d?



> Hi,
> 
> Thanks for your great work! can you share the config file for HiFi-Codec-24k-240d?

https://github.com/yangdongchao/AcademiCodec/blob/master/HiFi-Codec/param_config.json

**Comment by wblgers** [comment]
Thanks!
