### ISSUE TITLE
Training Soundstream on Single GPU

### ISSUE THREAD

**Issue by rishikksh20** [yangdongchao/AcademiCodec#2]
Hi @yangdongchao 
I am planning to training SoundStream codec from this repo to clean version of Libri light dataset + VCTK datasets and will open source the checkpoint, but I have single A100 for that, is it possible to train Soundstream on single A100 with lower batch size for longer time period?

**Comment by yangdongchao** [comment]
> Hi @yangdongchao I am planning to training SoundStream codec from this repo to clean version of Libri light dataset + VCTK datasets and will open source the checkpoint, but I have single A100 for that, is it possible to train Soundstream on single A100 with lower batch size for longer time period?

Yes, it just costs more time. Our code code suports one GPU to I belive train it. I believe it can be trained well. We expect your traning results.

**Comment by rishikksh20** [comment]
Any idea how many days of training it will takes to generate good result on single 3090 or A100 ?

**Comment by yangdongchao** [comment]
> Any idea how many days of training it will takes to generate good result on single 3090 or A100 ?

It relys on the number of your audio. If you use 1000 h data, I believe one 80G A100 only needs 1 weeks. I suggest you set 1 second segment input the model, and set larger batch size.

**Comment by rishikksh20** [comment]
ok thanks

**Comment by seastar105** [comment]
@rishikksh20 have successfully trained soundstream with default setting of this repo?
