### ISSUE TITLE
HiFi-Codec 训练时 0 卡被其他卡的线程占用少量显存

### ISSUE THREAD

**Issue by yt605155624** [yangdongchao/AcademiCodec#32]
如图：
![image](https://github.com/yangdongchao/AcademiCodec/assets/24568452/77e88170-ee5e-4a4b-bfd3-dd1340ea2cc1)
同样，在训练 SoundStorm 的时候，用了 HiFi-Codec 合成音频，也有类似问题
![image](https://github.com/yangdongchao/AcademiCodec/assets/24568452/35a9a5c8-4945-423a-b0e8-0f332c4f5a05)

**推测是 HiFi-Codec 在组网的时候可能某个模块的显存分配有问题**

可能是这里（尚未进一步定位） https://github.com/yangdongchao/AcademiCodec/blob/df5f3e4e7f43bb3a9ce73f755f839fc178b71cda/academicodec/models/hificodec/models.py#L513

**Comment by yuecanghai** [comment]
载入模型的时候其他卡先load到0卡再拷贝引起的，在train函数开头加一句torch.cuda.set_device(rank)就好了

**Comment by yt605155624** [comment]
@yuecanghai  赞，大佬验证过了嘛，可以提个 pr
