### ISSUE TITLE
Command line to train EnCodec

### ISSUE THREAD

**Issue by listener17** [yangdongchao/AcademiCodec#5]
Hi! Thanks for work. 
Do you have an example command line to train the EnCodec?

**Comment by yangdongchao** [comment]
> Hi! Thanks for work. Do you have an example command line to train the EnCodec?

`
python3 main3_ddp.py --BATCH_SIZE 16  --N_EPOCHS 300 \
        --save_dir path_to_save_log \
        --PATH  path_to_save_model \
        --train_data_path path_to_training_data \
        --valid_data_path path_to_val_data \
`
You just need to set the save_dir path, PATH, and your training dataset data path.

**Comment by listener17** [comment]
It seems to run SoundStream, if I want to train EnCodec?


/AcademiCodec/Encodec_24k_32d$ CUDA_VISIBLE_DEVICES=5 python3 main3_ddp.py --BATCH_SIZE 16  --N_EPOCHS 300 --save_dir ./log/ --PATH  ./save/ --train_data_path ./test/ --valid_data_path ./test/
n_q  2
soundstream  SoundStream(
  (encoder): SEANetEncoder(
    (model): Sequential(
      (0): SConv1d(
        (conv): NormConv1d(
          (conv): Conv1d(1, 32, kernel_size=(7,), stride=(1,))
          (norm): Identity()
        )
      )
      (1): SEANetResnetBlock(
        (block): Sequential(
          (0): ELU(alpha=1.0)
          (1): SConv1d(
            (conv): NormConv1d(
              (conv): Conv1d
.....

**Comment by listener17** [comment]
> > Hi! Thanks for work. Do you have an example command line to train the EnCodec?
> 
> 
> 
> `
> 
> python3 main3_ddp.py --BATCH_SIZE 16  --N_EPOCHS 300 \
> 
>         --save_dir path_to_save_log \
> 
>         --PATH  path_to_save_model \
> 
>         --train_data_path path_to_training_data \
> 
>         --valid_data_path path_to_val_data \
> 
> `
> 
> You just need to set the save_dir path, PATH, and your training dataset data path.

If I've got one GPU server (e.g., with 8 GPUs), and I want to use only one GPU (e.g., GPU number 0) how should I change the command line?

Only add --gpu 0?
