### ISSUE TITLE
About Fine-tuning pre-trained instructions

### ISSUE THREAD

**Issue by GitYesm** [yangdongchao/AcademiCodec#9]
Sorry Yang Sir  , I can't find about the command  instructions about  Fine-tuning the  pre-trained model  , cound you provide some information?

**Comment by yangdongchao** [comment]
> Sorry Yang Sir , I can't find about the command instructions about Fine-tuning the pre-trained model , cound you provide some information?

We have update the readme in Encodec_24k_240d. You can refer to it. More details, you should read the source code.

**Comment by GitYesm** [comment]
Thank you so much
